# Generated by Django 5.0 on 2024-04-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='ÖzelKullanıcı',
        ),
    ]
